---
- name: Example Simple Playbook
  hosts: localhost
  become: no

  tasks:     
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/stephenirven/ansible-test
      dest: /tmp/repos/ansible-test
      force: true
      single_branch: yes
      version: main

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /tmp/repos/ansible-test/
      dest: /tmp/repos/ansible-test/
      mode: '0777'        

#  - name: Change the working directory to somedir/ before executing the command
 #   ansible.builtin.shell: loghost.sh
  #  args:
   #   chdir: /tmp/
