---
- name: Example Simple Playbook
  hosts: localhost
  become: no

  tasks:
  - name: Copy 'test-file-1' from Local to Remote location
    copy:
      src: /tmp/output.txt
      dest: /tmp/output.txt
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/stephenirven/ansible-test
      dest: /tmp/repos/ansible-test
      single_branch: yes
      version: main

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /tmp/repos/ansible-test/
      dest: /tmp/repos/ansible-test/
      mode: '0777'      
