---
- name: Example Simple Playbook
  tasks:
  - name: Copy file example_file to /tmp with permissions
    ansible.builtin.copy:
      src: ./exercise.js
      dest: ./example_file
      mode: '0644'
