---
- name: Example Simple Playbook
  hosts: localhost
  become: no
  
  tasks:
  - name: Change the working directory to somedir/ before executing the command
    ansible.builtin.shell: date >> somelog.txt
    args:
      chdir: ~/

  - name: Example clone of a single branch
  ansible.builtin.git:
    repo: https://github.com/stephenirven/ansible-test
    dest: /tmp/repos
    single_branch: yes
    version: master
