---
- name: Example Simple Playbook
  hosts: localhost
  become: no
  
  tasks:
  - name: Copy file example_file to /tmp with permissions
    ansible.builtin.copy:
      src: /home/stephenirven/exercise.js
      dest: /home/stephenirven/example_file
      mode: '0644'
